# Generated by Django 5.2 on 2025-05-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='schedule_at',
            new_name='schedule_start',
        ),
        migrations.AddField(
            model_name='schedules',
            name='is_meal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='schedule_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
