# Generated by Django 5.2 on 2025-06-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_rename_schedule_at_schedules_schedule_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='with_chatroom',
            field=models.BooleanField(default=False),
        ),
    ]
