# Generated by Django 5.2 on 2025-07-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedules_with_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='with_chatroom',
            new_name='is_chatroom',
        ),
    ]
