# Generated by Django 5.2 on 2025-05-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='meal_schedule',
            new_name='schedule',
        ),
    ]
