# Generated by Django 5.2 on 2025-05-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_meal_schedule_participants_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='participants',
            new_name='participant',
        ),
    ]
