# Generated by Django 5.2 on 2025-06-30 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participants_participant'),
        ('schedules', '0003_schedules_with_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('schedule', 'participant')},
        ),
    ]
