# Generated by Django 5.2 on 2025-06-30 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('h_pending', '초대 허락 대기중'), ('pending', '초대 수락 대기중'), ('accepted', '초대 수락됨'), ('rejected', '초대 거절됨')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='InvitationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.chatroom')),
                ('blocking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocking_user', 'blocked_chatroom')},
            },
        ),
    ]
