# Generated by Django 5.2 on 2025-07-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_alter_invitation_status_invitationblock'),
        ('schedules', '0004_rename_with_chatroom_schedules_is_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invitationblock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invitation',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.schedules'),
        ),
        migrations.AddField(
            model_name='invitationblock',
            name='blocked_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.schedules'),
        ),
        migrations.DeleteModel(
            name='ChatParticipant',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='invitationblock',
            name='blocked_chatroom',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
