# Generated by Django 5.2 on 2025-07-02 03:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_add_schedule_fields_only'),
        ('schedules', '0004_rename_with_chatroom_schedules_is_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('schedule', 'from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='invitationblock',
            unique_together={('blocking_user', 'blocked_schedule')},
        ),
    ]
