# Generated by Django 5.2 on 2025-05-08 13:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=150)),
                ('rest_cuisine', models.CharField(choices=[('KR', '한식'), ('CN', '중식'), ('JP', '일식'), ('IT', '이탈리안'), ('FR', '프렌치'), ('TH', '태국'), ('VN', '베트남'), ('ET', '기타')], default='ET', max_length=2)),
                ('rest_address', models.CharField(max_length=255)),
                ('rest_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR')),
            ],
        ),
    ]
