# Generated by Django 5.2 on 2025-07-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.page'),
        ),
    ]
