# Generated by Django 5.2 on 2025-07-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('promo', '홍보'), ('review', '후기'), ('tip', '꿀TIP')], max_length=10, null=True),
        ),
    ]
