# Generated by Django 5.2 on 2025-05-14 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="requested_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
